export type S3Config = {
  aws_access: string;
  aws_secret: string;
  aws_bucket: string;
  aws_region: string;
};

export type Entry = {
  id: string;
  date: string;
  content: string;
  location?: string;
  timestamp: number;
  lastModified?: number; // auto-generated by idb
};

export type MasterIndex = Record<string, { lastModified: number; deleted: boolean }>;