export type S3Config = {
  aws_access: string;
  aws_secret: string;
  aws_bucket: string;
  aws_region: string;
};

export type Entry = {
  id: string;
  date: string;
  content: string;
  location?: string;
  timestamp: number;
  lastModified: number; // auto-generated by db
};

export interface DecodedEntry extends Entry {
  decodedContent: string;
}

export type MasterIndex = Record<string, MasterIndexEntry>;

export type MasterIndexEntry = {
  lastModified: number;
  deleted: boolean;
};